plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.2.1'
    id 'io.spring.dependency-management' version '1.1.4'
    id "io.sentry.jvm.gradle" version "4.14.1"
}

group = 'kr.inu-appcenter-portal'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

jacoco {
    toolVersion = "0.8.10"
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
    runtimeOnly 'com.h2database:h2'
    implementation'org.projectlombok:lombok'
    annotationProcessor'org.projectlombok:lombok'
    implementation 'com.google.code.gson:gson:2.8.9'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    implementation 'mysql:mysql-connector-java:8.0.32'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation 'org.jsoup:jsoup:1.15.3'
    implementation 'org.seleniumhq.selenium:selenium-java:4.18.1'

    //implementation "io.netty:netty-resolver-dns-native-macos:4.1.104.Final"
    runtimeOnly 'io.netty:netty-resolver-dns-native-macos:4.1.104.Final:osx-aarch_64'

    implementation 'org.apache.commons:commons-dbcp2:2.9.0'
    implementation 'com.oracle.database.jdbc:ojdbc11'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    implementation 'org.springframework.boot:spring-boot-starter-actuator' // Spring Actuator
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus' // Prometheus

}

// 제외할 디렉토리 및 파일 패턴을 공통 변수로 선언
ext.jacocoExcludes = [
        "**/generated/**", // Querydsl Qfile
        "**/dto/**",       // DTO 클래스
        "**/exception/**", // 커스텀 예외
        "**/config/**",    // 설정 파일
]

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('jacocoTestReport') {
    dependsOn(tasks.named('test')) // 테스트 실행 후 리포트 생성
    reports {
        xml.required = true // SonarQube를 위한 XML 리포트 생성
        html.required = true // 사람이 읽기 쉬운 HTML 리포트 생성
        csv.required = false // CSV 리포트는 비활성화
    }
    classDirectories.setFrom(
            files(classDirectories.files.collect { dir ->
                fileTree(dir) {
                    exclude jacocoExcludes // 리포트 생성에서 제외할 디렉토리와 파일 설정
                }
            })
    )

    // finalizedBy tasks.named('jacocoTestCoverageVerification') // 리포트 생성 후 검증
}
// 1. 서브모듈에서 *.yml 파일을 복사하는 작업 등록
tasks.register("copyPrivate", Copy) {
    from("$projectDir/INTIP-refactoring-yml-import") // 서브모듈 경로
    include("*.yml")                         // 복사할 파일 패턴 (*.yml)
    into("$projectDir/src/main/resources")   // 복사 대상 경로
}

// 2. processResources 작업에 copyPrivate 작업 의존 추가
tasks.named("processResources") {
    dependsOn("copyPrivate") // processResources는 copyPrivate 작업 후 실행
}

// 3. build 작업에도 copyPrivate 작업 의존 추가
tasks.named("build") {
    dependsOn("copyPrivate") // build 시에만 copyPrivate 작업이 실행되도록 설정
}


